# This workflow will build the CodeFlare Operator image and push it to the opendatahub image registry as well as update versions in the MakeFile and README

name: POST PR MERGE
on:
  workflow_dispatch:

jobs:
  pr_merged_by_bob_with_sync_title:
    runs-on: ubuntu-latest
    steps:
    - name: Delete remote branch
      run: |
        echo "Hello"
