# This workflow will build the CodeFlare Operator image and push it to the opendatahub image registry as well as update versions in the MakeFile and README

name: POST PR MERGE
on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  pr_merged_by_bob_with_sync_title:
    if: (github.event.pull_request.merged == true && github.event.pull_request.user.login == ${{ secrets.githubUserName }} && contains(github.event.pull_request.title, 'Sync with Upstream')) || github.event_name == 'workflow_dispatch'

    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Notify or perform actions
      run: |
        # You can put your notification or action steps here
        echo "PR by Bob with 'sync' title has been merged or workflow manually triggered."

